### ISSUE TITLE
code implementation

### ISSUE THREAD

**Issue by XuecWu** [ljj898/CMDFD-Dataset-and-Deepfake-Detection#1]
Thank you for your great work!
When will the code be available?

Looking forward to your reply.
Best regards,

**Comment by garlicyh** [comment]
+1

**Comment by ljj898** [comment]
Thank you for your interest. We will publish the code next week.

**Comment by mamarasulovs** [comment]
where is the code even after 2 weeks?

**Comment by ljj898** [comment]
Apologize for the delay. We now published our code. You can find it in the repository.
Thank you for all your patience!
